### ISSUE TITLE
Schemas folder not present after pip install

### ISSUE THREAD

**Issue by stiegerb** [dmwm/CMSMonitoring#6] opened 2019-02-06 13:53 UTC
When doing `pip install CMSMonitoring`, the schemas folder isn't present:

```
> from CMSMonitoring.StompAMQ import validate
> data = {"Status" : "Completed"}
> validate(data)
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-7-4193c763d3be> in <module>()
----> 1 validate(data)

/home/stiegerb/cms-htcondor-es-dev/venv/lib/python2.7/site-packages/CMSMonitoring/StompAMQ.pyc in validate(data, verbose)
     28     if 'payload' in data:
     29         doc = data['payload']
---> 30     for sname, schema in _schemas.schemas().items():
     31         if verbose:
     32             print('validate document {} against schema {} {}'.format(data, sname, schema))

/home/stiegerb/cms-htcondor-es-dev/venv/lib/python2.7/site-packages/CMSMonitoring/Validator.pyc in schemas(self)
     85             snames = os.listdir(fdir)
     86         except OSError:
---> 87             raise Exception('Invalid CMSMonitoring schemas area: {}'.format(fdir))
     88         except Exception as exp:
     89             raise Exception('Invalid CMSMonitoring schemas area: {}, error={}'.format(fdir, str(exp)))

Exception: Invalid CMSMonitoring schemas area: /home/stiegerb/cms-htcondor-es-dev/venv/lib/python2.7/site-packages//CMSMonitoring/schemas
```

Checking inside that directory, I see only the contents of `src/python/CMSMonitoring`:
```
/home/stiegerb/cms-htcondor-es-dev/venv/lib/python2.7/site-packages//CMSMonitoring/
total 64K
-rw-r--r--. 1 stiegerb zh 6.5K Feb  6 14:19 Validator.py
-rw-r--r--. 1 stiegerb zh 8.2K Feb  6 14:19 StompAMQ.py
-rw-r--r--. 1 stiegerb zh 6.0K Feb  6 14:19 monit.py
-rw-r--r--. 1 stiegerb zh    0 Feb  6 14:19 __init__.py
-rw-r--r--. 1 stiegerb zh 9.7K Feb  6 14:19 StompAMQ.pyc
-rw-r--r--. 1 stiegerb zh 8.4K Feb  6 14:19 Validator.pyc
-rw-r--r--. 1 stiegerb zh  159 Feb  6 14:19 __init__.pyc
-rw-r--r--. 1 stiegerb zh 6.4K Feb  6 14:19 monit.pyc
```

I tried this inside a virtualenv, but I don't believe that makes a difference.

**Comment by vkuznet** [comment] 2019-02-07 15:31
Benjamin, thanks for report, apparently I didn't check install area. The issue is fixed in 0.0.5 version and it is uploaded to pypi.

**Closed by vkuznet** 2019-02-07 15:31 UTC
